services:
  postgres:
    image: postgres:14
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d postgres"]
      interval: 5s
      retries: 5
      timeout: 5s
    networks:
      - mynetwork
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  fastapi_app:
    build: ./backend
    container_name: fastapi_app
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./backend:/app
      - ./goodreads_reviews_spoiler_raw.json:/app/goodreads_reviews_spoiler_raw.json
      - ./updated_books.csv:/app/updated_books.csv
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  idm_db:
    image: postgres:14
    container_name: idm_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: idm_db
    volumes:
      - db_data_idm:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d idm_db"]
      interval: 5s
      retries: 5
      timeout: 5s
    networks:
      - mynetwork

  idm_service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: idm_service
    ports:
      - "50051:50051"
    environment: 
      DATABASE_URL: "postgresql://user:password@idm_db:5432/idm_db"
    depends_on:
      idm_db:
        condition: service_healthy
    networks:
      - mynetwork

  idm_api:
    build:
      context: ./auth
      dockerfile: Dockerfile.api
    container_name: idm_api
    ports:
      - "8080:8080"
    depends_on:
      idm_db:
        condition: service_healthy
    networks:
      - mynetwork


volumes:
  db_data:
  db_data_idm:

networks:
  mynetwork:
    driver: bridge