version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: spax
      POSTGRES_PASSWORD: spax
      POSTGRES_DB: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  flask_app:
    build: ./backend
    container_name: flask_app
    environment:
      POSTGRES_USER: spax
      POSTGRES_PASSWORD: spax
      POSTGRES_DB: postgres
      FLASK_ENV: development
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    depends_on:
      - postgres

networks:
  mynetwork:
    driver: bridge
